=== C2SP/wycheproof/schemas/pbe_test_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "PbeTestGroup": {
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "PbeTest"
          ]
        },
        "source": {
          "$ref": "common.json#/definitions/Source"
        },
        "tests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PbeTestVector"
          }
        }
      },
      "required": ["type", "tests"],
      "additionalProperties": false
    },
    "PbeTestVector": {
      "type": "object",
      "properties": {
        "tcId": {
          "type": "integer",
          "description": "Identifier of the test case"
        },
        "comment": {
          "type": "string",
          "description": "A brief description of the test case"
        },
        "flags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "A list of flags"
        },
        "password": {
          "type": "string",
          "format": "HexBytes",
          "description": "The password as a hex-encoded byte string. PBKDF takes an arbitrary octet string as input. The conversion from passwords given as strings to octet strings is not defined in the RFC."
        },
        "salt": {
          "type": "string",
          "format": "HexBytes",
          "description": "The salt for the key derivation"
        },
        "iterationCount": {
          "type": "integer",
          "description": "The number of iterations for the key derivation"
        },
        "iv": {
          "type": "string",
          "format": "HexBytes",
          "description": "The IV used for the encryption"
        },
        "msg": {
          "type": "string",
          "format": "HexBytes",
          "description": "The message to encrypt"
        },
        "ct": {
          "type": "string",
          "format": "HexBytes",
          "description": "The ciphertext"
        },
        "result": {
          "$ref": "common.json#/definitions/Result"
        }
      },
      "required": ["tcId", "comment", "flags", "password", "salt", "iterationCount", "iv", "msg", "ct", "result"],
      "additionalProperties": false
    }
  },
  "properties": {
    "algorithm": {
      "enum": [
        "PbeWithHmacSha1AndAes_128",
        "PbeWithHmacSha1AndAes_192",
        "PbeWithHmacSha1AndAes_256",
        "PbeWithHmacSha224AndAes_128",
        "PbeWithHmacSha224AndAes_192",
        "PbeWithHmacSha224AndAes_256",
        "PbeWithHmacSha256AndAes_128",
        "PbeWithHmacSha256AndAes_192",
        "PbeWithHmacSha256AndAes_256",
        "PbeWithHmacSha384AndAes_128",
        "PbeWithHmacSha384AndAes_192",
        "PbeWithHmacSha384AndAes_256",
        "PbeWithHmacSha512AndAes_128",
        "PbeWithHmacSha512AndAes_192",
        "PbeWithHmacSha512AndAes_256"
      ]
    },
    "generatorVersion": {
      "type": "string",
      "description": "DEPRECATED: prefer \"source\" property in test group",
      "deprecated": true
    },
    "header": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Additional documentation"
    },
    "notes": {
      "$ref": "common.json#/definitions/Notes"
    },
    "numberOfTests": {
      "type": "integer",
      "description": "The number of test vectors in this test"
    },
    "schema": {
      "enum": [
        "pbe_test_schema.json"
      ]
    },
    "testGroups": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/PbeTestGroup"
      }
    }
  },
  "required": ["algorithm", "header", "notes", "numberOfTests", "schema", "testGroups"],
  "additionalProperties": false
}

=== C2SP/wycheproof/testvectors_v1/pbes2_hmacsha256_aes_256_test.json
{
  "algorithm": "PbeWithHmacSha256AndAes_256",
  "schema": "pbe_test_schema.json",
  "numberOfTests": 84,
  "header": [
    "Test vector of type PbeTest are used for PBES1 or PBES2."
  ],
  "notes": {
    "Ascii": {
      "bugType": "FUNCTIONALITY",
      "description": "The test vector contains a password consisting of ASCII characters."
    },
    "BmpString": {
      "bugType": "FUNCTIONALITY",
      "description": "The test vectors contains a password that is a valid BMPString as used in RFC 7292. This RFC uses big endian encoding and a null terminator."
    },
    "NonUtf8": {
      "bugType": "FUNCTIONALITY",
      "description": "The test vector contains a password that is not a valid UTF-8 string."
    },
    "Printable": {
      "bugType": "FUNCTIONALITY",
      "description": "The test vector contains a password consisting of printable ASCII characters."
    },
    "Utf8": {
      "bugType": "FUNCTIONALITY",
      "description": "The test vector contains a password that is a valid UTF-8 string."
    }
  },
  "testGroups": [
    {
      "type": "PbeTest",
      "source": {
        "name": "google-wycheproof",
        "version": "0.9"
      },
      "tests": [
        {
          "tcId": 1,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "7743656734722c30",
          "salt": "fcd9a324f025ef40",
          "iterationCount": 4096,
          "iv": "42f02ff71b8524d1678ab2e34f9e7d47",
          "msg": "",
          "ct": "e03383efa5cfd120d5df634b2448b103",
          "result": "valid"
        },
        {
          "tcId": 2,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "64395f4b48295839",
          "salt": "bfb221ba6de64926",
          "iterationCount": 4096,
          "iv": "7a735848780923657c0c54bc2ff0d9f8",
          "msg": "a3",
          "ct": "6d2158ca2020909e87fbae167a3090e0",
          "result": "valid"
        },
        {
          "tcId": 3,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "3a787e4c2c604d70",
          "salt": "dc64f1fd4705b4e5",
          "iterationCount": 4096,
          "iv": "579ff2437d6739742421b6e4e70d5c27",
          "msg": "4204",
          "ct": "e4cd170b4591a8b944654973dd669350",
          "result": "valid"
        },
        {
          "tcId": 4,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "2a67656a66296120",
          "salt": "4c379a2bd962d19a",
          "iterationCount": 4096,
          "iv": "5bff9a5e8692229679cbd70fcfdebb74",
          "msg": "ceb541",
          "ct": "c345ad62e7745cc532ad0b90a34061ed",
          "result": "valid"
        },
        {
          "tcId": 5,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "3b55267d5f4b2d4c",
          "salt": "08e041282eed4f00",
          "iterationCount": 4096,
          "iv": "17c5e988149370694c1b3b8cb0e44225",
          "msg": "10d032a7",
          "ct": "66454530862777c38563f0221d90e428",
          "result": "valid"
        },
        {
          "tcId": 6,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "4f317e2e525e517a",
          "salt": "bd5c4b6f25a1f6ff",
          "iterationCount": 4096,
          "iv": "76e5e3eb771a4daec6fabdc0b0793195",
          "msg": "29d9f1a701",
          "ct": "7b322ef8ff216f1c8735daeeb05ea4b7",
          "result": "valid"
        },
        {
          "tcId": 7,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "6557766473282375",
          "salt": "ea1efbb1c86b0c06",
          "iterationCount": 4096,
          "iv": "1f186ad98435e90fd7700695c986ef78",
          "msg": "6f124d8a8248",
          "ct": "de60d73214727446d883429735e79666",
          "result": "valid"
        },
        {
          "tcId": 8,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "543a5f48765a2542",
          "salt": "f308bbcca74a2224",
          "iterationCount": 4096,
          "iv": "26bbbf2e18f06a4524e13bfd1ac00b37",
          "msg": "a1163153287dfe",
          "ct": "987adc98e8ca6f1e71381be99830df18",
          "result": "valid"
        },
        {
          "tcId": 9,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "695a3c642f457a52",
          "salt": "7af3b0005c594502",
          "iterationCount": 4096,
          "iv": "6d9e8ea3d6ed355bf5e65b12995dbf6a",
          "msg": "9b29df8b3b9862f4",
          "ct": "4bcb30bde11dff1050914aed60ed7293",
          "result": "valid"
        },
        {
          "tcId": 10,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "2a772a233f216e60",
          "salt": "172d5f4595c220dd",
          "iterationCount": 4096,
          "iv": "a5941967d4f6934431bd9951e20a93a6",
          "msg": "fe51cf84289221b894",
          "ct": "fa35a45533f263c9445b5f6f12bc788c",
          "result": "valid"
        },
        {
          "tcId": 11,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "793c43623652216f",
          "salt": "d1d722eee2c5ebef",
          "iterationCount": 4096,
          "iv": "5cfe832947ec659f6847277ec1fab2f9",
          "msg": "696eb8b4e6b2015abb91",
          "ct": "cd145d184b9adb2344408f6e4a152624",
          "result": "valid"
        },
        {
          "tcId": 12,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "4854515c222a2230",
          "salt": "843f5ff28978f214",
          "iterationCount": 4096,
          "iv": "430b247a435124754c83cc11203f18bd",
          "msg": "d8405be7823b472459a2fc",
          "ct": "04de69023e941da4a39b0557bb550cff",
          "result": "valid"
        },
        {
          "tcId": 13,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "48682a4d34266b40",
          "salt": "783f344a1fa7c9a8",
          "iterationCount": 4096,
          "iv": "c707947121e5fc2da16990a78772e0ab",
          "msg": "56c73b781c1bff72a8ae7faf",
          "ct": "c53d0f69ae2ec9bd3f0678284db2588b",
          "result": "valid"
        },
        {
          "tcId": 14,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "293a746531294d5c",
          "salt": "2c75641f991eb10b",
          "iterationCount": 4096,
          "iv": "96dabd858e4187d0e50f8299ab60f029",
          "msg": "b07e8bbb45e9a17c124f6d5129",
          "ct": "899c4064bc1c6b8488fe4bcb5ff28f89",
          "result": "valid"
        },
        {
          "tcId": 15,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "353377343f482b65",
          "salt": "cf1620e7aabb73b7",
          "iterationCount": 4096,
          "iv": "8e6dd70b1dd1c39d0b8b593c556d812b",
          "msg": "ff89eb184de11579cae7d110a350",
          "ct": "6fcd290304343442991e2527dc7aa371",
          "result": "valid"
        },
        {
          "tcId": 16,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "614e2d4634335721",
          "salt": "6dffc1db31767608",
          "iterationCount": 4096,
          "iv": "78c899bcdc4cf7d933ddc9016bc6e64e",
          "msg": "5e859aac690c85646ffb3f2bbb0d9c",
          "ct": "5cdc1029cf192b802e534280dbdc21e8",
          "result": "valid"
        },
        {
          "tcId": 17,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "6f5330325e22574e",
          "salt": "798acc7c76739d75",
          "iterationCount": 4096,
          "iv": "5bfcfd6d7013eb8828f72455d7535c77",
          "msg": "86059dc647ba7d0067099e16c3da8bb6",
          "ct": "03a73bc4a4d35d9b774b25b559676161275661eaae98fe00bde7ef19ada52256",
          "result": "valid"
        },
        {
          "tcId": 18,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "3972245623494f42",
          "salt": "da5421f23ac5b5e1",
          "iterationCount": 4096,
          "iv": "12293114ddb85319240682c1765e4533",
          "msg": "fc9349cbd8c277786c888f3254342431a8",
          "ct": "e2e31d9010e139fc6820af5f9d4fab12e24e1a442e2becf285fe1a3b7a310d2b",
          "result": "valid"
        },
        {
          "tcId": 19,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "464d2f76752b4d63",
          "salt": "8cfea3c6783cfc41",
          "iterationCount": 4096,
          "iv": "9c84fe91476ab1c6ed30db9bb7f60280",
          "msg": "ad10a3cdef856b0632f7ce200c11f6c569d2",
          "ct": "c4eb3baddbab3bc06ee9513b0b4aa13ed7fa423207b55443a38443cd0e254c6b",
          "result": "valid"
        },
        {
          "tcId": 20,
          "comment": "printable password",
          "flags": [
            "Printable"
          ],
          "password": "7951437c2b6f7079",
          "salt": "caada2e55c49492f",
          "iterationCount": 4096,
          "iv": "3a0185b1423310796b052e9128334b04",
          "msg": "be82c331a83dd0c472abc6ae8725d2ba48b3ad",
          "ct": "f33ee7dec0cffb0cd62b0396b94c885d139d0078bdbb11ad944b396fc63f7318",
          "result": "valid"
        },
        {
          "tcId": 21,
          "comment": "printable password",
